/* Automatically generated by create_config - do not modify */
#define CONFIG_OPENCORES_ETH 1
#define CONFIG_PFLASH_CFI01 1
#define CONFIG_SEMIHOSTING 1
#define CONFIG_SERIAL 1
#define CONFIG_XTENSA_SIM 1
#define CONFIG_XTENSA_XTFPGA 1
