/* Automatically generated by create_config - do not modify */
#define TARGET_NIOS2 1
#define TARGET_NAME "nios2"
#define TARGET_NIOS2 1
#define CONFIG_USER_ONLY 1
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-nios2"
#define CONFIG_LINUX_USER 1
#define CONFIG_I386_DIS 1
#define CONFIG_NIOS2_DIS 1
