export OCAMLMAKEFILE = ../ocaml/OCamlMakefile
                                                                                          
RESULT = imm_parser

export SOURCES = \
    ast.ml parser.mly lexer.mll imm_parser.ml

all: dncl

include $(OCAMLMAKEFILE)
