/* Automatically generated by create_config - do not modify */
#define CONFIG_ADLIB 1
#define CONFIG_CS4231A 1
#define CONFIG_GUS 1
#define CONFIG_ISA_BUS 1
#define CONFIG_NE2000_COMMON 1
#define CONFIG_NE2000_ISA 1
#define CONFIG_PARALLEL 1
#define CONFIG_PCKBD 1
#define CONFIG_PS2 1
#define CONFIG_PTIMER 1
#define CONFIG_PUV3 1
#define CONFIG_SB16 1
#define CONFIG_SERIAL 1
#define CONFIG_SERIAL_ISA 1
#define CONFIG_WDT_IB700 1
