/* Automatically generated by create_config - do not modify */
#define TARGET_HPPA 1
#define TARGET_NAME "hppa"
#define TARGET_HPPA 1
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_SOFTMMU 1
#define TARGET_SUPPORTS_MTTCG 1
#define CONFIG_I386_DIS 1
#define CONFIG_HPPA_DIS 1
