# Automatically generated by configure - do not modify
TARGET_X86_64=y
TARGET_NAME=x86_64
TARGET_BASE_ARCH=i386
TARGET_ABI_DIR=x86_64
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-x86_64"
CONFIG_LINUX_USER=y
TARGET_XML_FILES= /home/ppi/dbt/pattern-dbt/qemu-4.1.0_dbt_0511/gdb-xml/i386-64bit.xml
CONFIG_I386_DIS=y
CONFIG_I386_DIS=y
LDFLAGS+= 
QEMU_CFLAGS+=
