/* Automatically generated by create_config - do not modify */
#define TARGET_TILEGX 1
#define TARGET_NAME "tilegx"
#define TARGET_TILEGX 1
#define CONFIG_USER_ONLY 1
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-tilegx"
#define CONFIG_LINUX_USER 1
#define CONFIG_I386_DIS 1
