/* Automatically generated by create_config - do not modify */
#define TARGET_OPENRISC 1
#define TARGET_NAME "or1k"
#define TARGET_OPENRISC 1
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1
