/* Automatically generated by create_config - do not modify */
#define TARGET_RISCV64 1
#define TARGET_NAME "riscv64"
#define TARGET_RISCV 1
#define CONFIG_USER_ONLY 1
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-riscv64"
#define CONFIG_LINUX_USER 1
#define CONFIG_I386_DIS 1
#define CONFIG_RISCV_DIS 1
