# Automatically generated by configure - do not modify
TARGET_RISCV64=y
TARGET_NAME=riscv64
TARGET_BASE_ARCH=riscv
TARGET_ABI_DIR=riscv
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-riscv64"
CONFIG_LINUX_USER=y
TARGET_XML_FILES= /home/ppi/dbt/pattern-dbt/qemu-4.1.0_dbt_0511/gdb-xml/riscv-64bit-cpu.xml /home/ppi/dbt/pattern-dbt/qemu-4.1.0_dbt_0511/gdb-xml/riscv-64bit-fpu.xml /home/ppi/dbt/pattern-dbt/qemu-4.1.0_dbt_0511/gdb-xml/riscv-64bit-csr.xml
CONFIG_I386_DIS=y
CONFIG_RISCV_DIS=y
LDFLAGS+= 
QEMU_CFLAGS+=
