/* Automatically generated by create_config - do not modify */
#define CONFIG_ALTERA_TIMER 1
#define CONFIG_NIOS2 1
#define CONFIG_NIOS2_10M50 1
#define CONFIG_NIOS2_GENERIC_NOMMU 1
#define CONFIG_PTIMER 1
#define CONFIG_SEMIHOSTING 1
#define CONFIG_SERIAL 1
