/* Automatically generated by create_config - do not modify */
#define TARGET_OPENRISC 1
#define TARGET_NAME "or1k"
#define TARGET_OPENRISC 1
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_USER_ONLY 1
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-or1k"
#define CONFIG_LINUX_USER 1
#define CONFIG_I386_DIS 1
