# Automatically generated by configure - do not modify
SRC_PATH=/home/ppi/dbt/pattern-dbt/qemu-4.1.0_dbt_0511/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
