# Automatically generated by configure - do not modify
TARGET_PPC=y
TARGET_NAME=ppc
TARGET_BASE_ARCH=ppc
TARGET_ABI_DIR=ppc
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
TARGET_XML_FILES= /home/ppi/dbt/pattern-dbt/qemu-4.1.0_dbt_0511/gdb-xml/power-core.xml /home/ppi/dbt/pattern-dbt/qemu-4.1.0_dbt_0511/gdb-xml/power-fpu.xml /home/ppi/dbt/pattern-dbt/qemu-4.1.0_dbt_0511/gdb-xml/power-altivec.xml /home/ppi/dbt/pattern-dbt/qemu-4.1.0_dbt_0511/gdb-xml/power-spe.xml
CONFIG_I386_DIS=y
CONFIG_PPC_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
